name: labwallet
description: A Labcoin Wallet CLI
version: 0.0.1
author: Konstantin Ullrich <konstantinullrich12@gmail.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.6.0
  crypto: ^2.1.5
  labcoin_sdk:
    version: ^0.0.2
    git: https://github.com/LabcoinProject/sdk.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.5
